### ISSUE TITLE
[bug] 更新agp8.0后会导致主活动无法打开，除非关闭混淆。

### ISSUE THREAD

**Issue by hosizoraru** [577fkj/blockmiui#26]
首先说结论：
- agp8.0+不混淆，可以正常打开
- agp8.0+混淆，打开就fc
- agp7.4.2+混淆，正常。  

希望能解决一下，否则关闭混淆关闭资源收缩后apk大小会暴涨。问过yife才知道原来是混淆的问题，他说应该是混淆没配置好。
以下是日志：
```
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: 2106118C
[Display]: TKQ1.220829.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: ja_JP
[Process ID]: 6705
[CPU ABI]: arm64-v8a
[Package Name]: com.lt2333.simplicitytools
[Version Name]: 1.7.5-Voyager
[Version Code]: 76
[Error Type]: JVM
[Crash Time]: 2023-04-17T18:22:50.711
[Stack Trace]:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lt2333.simplicitytools/com.lt2333.simplicitytools.activity.MainActivity}: java.lang.Exception: Page must be annotated with BMMainPage or BMMenuPage or BMPage
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3825)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3971)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:210)
 at android.os.Looper.loop(Looper.java:299)
 at android.app.ActivityThread.main(ActivityThread.java:8261)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.Exception: Page must be annotated with BMMainPage or BMMenuPage or BMPage
 at cn.fkj233.ui.activity.MIUIActivity.initAllPage(Unknown Source:55)
 at cn.fkj233.ui.activity.MIUIActivity.onCreate(Unknown Source:317)
 at com.lt2333.simplicitytools.activity.MainActivity.onCreate(Unknown Source:26)
 at android.app.Activity.performCreate(Activity.java:8516)
 at android.app.Activity.performCreate(Activity.java:8480)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3806)
 ... 12 more
```

**Comment by 577fkj** [comment]
keep掉注解就行了

**Comment by hosizoraru** [comment]
目前是解决了，注释+开兼容模式，也就是说大概要用到以下的：
android.nonTransitiveRClass=false
android.enableR8.fullMode=false
-keepattributes RuntimeVisibleAnnotations
